Feature 8 authentication
Finder-2023/finder_backend pull request #12
Opened 2023-04-30 16:34 UTC by gaguriee

Authentication based on Spring Security & JWT token

2023-05-01 16:49 UTC, happyjamy reviewed
우선 Auth 까지만 코드리뷰 햇습니다

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/controller/AuthController.java
> +  @ResponseBody
@RestController 하면 @ResponseBody 안붙여도 됩니다.
@RestController = @Controller 애노테이션과 @ResponseBody 애노테이션을 합친 것

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/controller/AuthController.java
> +    return ResponseEntity.ok()
token 을 바로 return 안하고 ResponseEntity를 따로 만든 이유가 뭘까요?

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/controller/AuthController.java
> +    Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
이거 서비스 안에다가 logout 함수로넣어주시면 안될까요

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/controller/AuthController.java
> +    Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
Circular reference 문제 있는거 아니면 컨트롤러 단에서 로직 쓰지 말아주세요ㅠㅠ

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/controller/AuthController.java
> +    return ResponseEntity.ok()
여기도 위에서 말한것 처럼 토큰 바로 안보내고 ResponseEntity 만든 이유??

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/dto/Authority.java
Dto 랑 entity 랑 달라요!! 이거 폴더명 Entity로 바꿔주세용

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/dto/User.java
> +  private Date birth;
java java.util.Date 클래스는 JDK 1.0에서 등장한 날짜와 시간 정보를 다루는 클래스로, 기본적으로 long 타입의 숫자로 표현됩니다. 이 숫자는 UTC 기준으로 1970년 1월 1일 00:00:00부터 현재까지의 밀리초(millisecond) 수를 나타냅니다. 이 클래스는 많은 기능을 제공하지만, 멀티스레딩 환경에서 안전하지 않아, 대체 클래스인 java.time 패키지의 클래스를 사용할 것을 권장합니다.

java.time.LocalDate 클래스는 Java 8에서 등장한, 날짜 정보를 다루는 클래스입니다. 이 클래스는 연도, 월, 일을 나타내는 객체를 생성하여, 날짜 정보를 다룹니다. 이 클래스는 불변(immutable) 클래스로 설계되어 있어, 스레드 안전성이 보장되고, 자주 사용되는 날짜 연산을 간편하게 처리할 수 있습니다. 또한, LocalDate 클래스는 시간 정보가 없는 단순한 날짜 정보만 다루므로, 특정 시간대의 로컬 시간 정보를 다루기 위해서는 LocalDateTime 클래스를 사용해야 합니다.

**Date 말고 LocalDate 씁시다!**

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/dto/User.java
> +@Getter
@Data 이걸로 바꾸는거 어떨까요?
**@Data 는 toString(), equals(), hashCode(), getter, setter 등의 메소드를 자동으로 생성**

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/dto/User.java
> +  private Timestamp created_at;
여기도 LocalDateTime 으로 변경 어떠세요?

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/dto/User.java
자바 컨벤션에 따르면 변수명은 코드 내에서 카멜케이스로 쓰는게 좋습니다. DB 안에서는 스네이크 케이스로 써도 여기서는 다 카멜케이스로 변경 부탁드려요

이거 왜 Auth 폴더에 있나요ㅠㅠ user로 옮겨주세요

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/dto/User.java
> +  @ManyToMany
나중에 만나서 설명 좀 해주세요!

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/event/LoginRequest.java
> +  private String password;
이렇게 주고 받을꺼면 https 해야될듯

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/event/PasswordResetRequest.java
> +  private String imp_uid;
이 변수는 뭐징

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/event/SignupRequest.java
> +//  @NotNull
주석 처리한거는 없애주세용

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/jwt/filter/JwtFilter.java
> +    throw new RuntimeException();
무슨 에러인지 명시해주세요!

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/jwt/filter/JwtFilter.java
> +        log.info("invalid jwt token");
여기서 에러 리턴해야되지 않나요?

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/service/AuthService.java
> +    User user = User.create(
@Mapper 로 바꿔보는건 어떤가요??

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/service/AuthService.java
> +  private final AuthenticationManagerBuilder authenticationManagerBuilder;
72,73 맨 위로 빼주세요

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/jwt/TokenProvider.java
> +  } // InitializingBean 인터페이스를 구현한 빈이 초기화될 때 호출되는 메소드
굿굿굿굿굿 나 이거 찾다가 못찾았는데 굳

2023-05-01 16:49 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/jwt/TokenProvider.java
> +    var accessToken= Jwts.builder()
userId 는 어딨나요??

2023-05-02 01:58 UTC, happyjamy requested changes
Test 빼고 다 리뷰 했습니다! 고쳐서 다시 pr 해주시고 모르는거 물어봐 주세요

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/User/Interface/UserRepository.java
이것도 왜 Repository 폴더에 없고 Interface에 있나욧

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/User/controller/UserController.java
> +      throw new ResponseStatusException(HttpStatus.BAD_REQUEST, ex.getMessage());
이거 customException 으로 바꿔주세요!

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/User/controller/UserController.java
> +  // 회원 정보 가져오기 (ADMIN) : Admin 관리용,
이런건 Admin 도메인으로 빼는게 어떨까?

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/User/service/UserService.java
> +@Transactional(readOnly = true) // 읽기 작업만 수행하고 데이터를 변경하지 않음
위에다 한번에 붙여줘도 되나?

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/User/service/UserService.java
> +    if (userInDb == null) {
Optional<User> userInDbOptional = userRepository.findByEmail(signupRequest.getEmail());
if(userInDbOptional.isPresent()) {
    // 이미 가입된 사용자가 존재하는 경우 처리
    throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "User already exists with this email");
} else {
    // 사용자 생성 및 저장 등의 로직 수행
    // ...
}

요런식으로도 좋을 것 같아요

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/User/service/UserService.java
> +      if (! userInDb.getNick_name().equals(userRequest.getNick_name())){
46번째 줄이랑 동일하네용

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/User/service/UserService.java
> +      userInDb.setUri(userRequest.getUri());
https://velog.io/@neptunes032/JPA-%EC%98%81%EC%86%8D%EC%84%B1-%EC%BB%A8%ED%85%8D%EC%8A%A4%ED%8A%B8%EB%9E%80

이거 한번에 실행되는게 아니면 save 말고 따로 쿼리를 하나씩 생성하는게 좋을것 같아요

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/User/service/UserService.java
> +        .flatMap(userRepository::findOneWithAuthoritiesById); // 데이터 평면화
이게뭐죵..?

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/User/service/UserService.java
> +  public User editProfile(UserRequest userRequest) throws CustomException {
본인만 변경할 수 있게 로직 넣은 거 맞나요??

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/User/event/UserRequest.java
> +  private Timestamp last_accessed;
LocalDateTime

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/User/event/UserRequest.java
vaildation 넣어줘야 할듯

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/exception/ErrorResponse.java
> +                        .missValue(value)
이름 바꿔야 할듯

2023-05-02 01:58 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(value = { CustomException.class})
CustomException 에 대한 에러 처리만 되어 있어서 다른 에러를 throw 한게 있다면 여기서 따로 처리 해주는 로직 넣어햐됩니다

2023-05-02 02:31 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/Auth/dto/User.java
> +  @JsonIgnore
왜 ignore 하셨나요

2023-05-02 02:43 UTC, happyjamy commented on src/main/java/com/finder/finder_backend/domain/User/Interface/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
왜 class 가 아니지

2023-05-02 15:23 UTC, gaguriee commented on src/main/java/com/finder/finder_backend/domain/User/service/UserService.java
> +    if (userInDb == null) {
요부분은 추가 설명 부탁드릴게용 editTable 부분이 맞나요??

2023-05-02 15:33 UTC, gaguriee commented on src/main/java/com/finder/finder_backend/domain/Auth/jwt/TokenProvider.java
> +    var accessToken= Jwts.builder()
.setSubject(authentication.getName()) : subject을 phone number에서 userId로 변경했습니다

2023-05-02 15:48 UTC, gaguriee commented on src/main/java/com/finder/finder_backend/domain/User/service/UserService.java
> +@Transactional(readOnly = true) // 읽기 작업만 수행하고 데이터를 변경하지 않음
전체 클래스에 @Transactional(readOnly = true) 어노테이션을 선언하면 데이터 변경이 일어나지 않도록 막을 수 있고, 일부 데이터 변경이 필요한 메소드에서는 @Transactional(readOnly = false) 어노테이션을 추가하여 읽기/쓰기 트랜젝션을 허용해주는 방식으로 부적합한 데이터 변경을 방지해줍니당

2023-05-02 15:52 UTC, gaguriee commented on src/main/java/com/finder/finder_backend/domain/User/service/UserService.java
> +        .flatMap(userRepository::findOneWithAuthoritiesById); // 데이터 평면화
flatMap같은건 Optional<>이 여러번 중첩되는 경우에 평탄화하기위해 사용됩니다! 중첩된 Optional 구조를 없애고 단일 요소로 바꿔주는 역할을 합니당

2023-05-02 15:54 UTC, gaguriee commented on src/main/java/com/finder/finder_backend/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(value = { CustomException.class})
확인했습니당

2023-05-02 16:13 UTC, gaguriee commented on src/main/java/com/finder/finder_backend/domain/User/Interface/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
JpaRepository를 검색해보면 될거같습니당

2023-05-02 16:14 UTC, gaguriee commented on src/main/java/com/finder/finder_backend/domain/Auth/dto/User.java
> +  @JsonIgnore
이거 내일 저와 이야기해주세요

2023-05-02 16:28 UTC, gaguriee commented on src/main/java/com/finder/finder_backend/domain/Auth/event/PasswordResetRequest.java
> +  private String imp_uid;
아임포트 본인인증 id입니다

2023-05-03 03:04 UTC, closed without merging